title: Danty Cook Portfolio
description: Data Analytics & Data Engineering Projects
url: "https://caprikey.github.io"
baseurl: "/portfolio-starter"

permalink: pretty

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
